import { test } from 'node:test'
import assert from 'node:assert/strict'
import { universalMetrics, englishMetrics, computeFingerprint, PERSON_MARKERS } from '../scripts/lib/metrics.mjs'

const strings = [
  'Your campaign is scheduled.',
  'Nice work!',
  'Want to schedule another one?',
  'We sent it - the report is ready; check your inbox.'
]

test('universal metrics count structure and punctuation', () => {
  const m = universalMetrics({ strings, headings: [], locale: 'en' })
  assert.equal(m.sentenceCount, 4)
  assert.equal(m.wordCount, 21)
  assert.equal(m.exclamationRate, 0.25)
  assert.equal(m.questionRate, 0.25)
  assert.ok(m.meanSentenceLength > 0)
  assert.ok(m.sentenceLengthSd >= 0)
  assert.equal(m.semicolonPer1000Words > 0, true)
  assert.equal(m.emojiPer1000Words, 0)
})

test('heading case ratio counts Title Case among multi-word headings', () => {
  const m = universalMetrics({
    strings: ['x'],
    headings: ['Schedule A Campaign', 'Schedule a campaign', 'Reports', 'Set Up Billing'],
    locale: 'en'
  })
  assert.equal(m.headingTitleCaseRatio, 0.667, 'Reports is single-word and excluded')
})

test('person marker rates are null for a locale with no marker set', () => {
  assert.ok(PERSON_MARKERS.en.second.includes('you'))
  const en = universalMetrics({ strings: ['You can schedule it. We will send it.'], headings: [], locale: 'en' })
  assert.ok(en.secondPersonPer1000Words > 0)
  assert.ok(en.firstPersonPer1000Words > 0)

  const xx = universalMetrics({ strings: ['Neco tady je.'], headings: [], locale: 'xx' })
  assert.equal(xx.firstPersonPer1000Words, null)
  assert.equal(xx.secondPersonPer1000Words, null)
})

test('empty input yields nulls, not zeros', () => {
  const m = universalMetrics({ strings: [], headings: [], locale: 'en' })
  assert.equal(m.sentenceCount, 0)
  assert.equal(m.meanSentenceLength, null)
  assert.equal(m.exclamationRate, null)
  assert.equal(m.headingTitleCaseRatio, null)
})

test('english metrics detect contractions, passive, imperative, hedges, intensifiers', () => {
  const m = englishMetrics({
    strings: [
      "We didn't send it.",
      'The report was generated by the system.',
      'Open the settings page.',
      'This might possibly work.',
      'It is very extremely good.'
    ]
  })
  assert.ok(m.contractionPer1000Words > 0)
  assert.equal(m.passiveRate > 0, true)
  assert.equal(m.imperativeOpenerRate > 0, true)
  assert.ok(m.hedgePer1000Words > 0)
  assert.ok(m.intensifierPer1000Words > 0)
  assert.ok(m.readingGrade > 0)
  assert.ok(m.longWordRate >= 0)
})

test('oxford comma rate is measured only over serial-list candidates', () => {
  const withOxford = englishMetrics({ strings: ['Email, social, and web.'] })
  assert.equal(withOxford.oxfordCommaRate, 1)
  const without = englishMetrics({ strings: ['Email, social and web.'] })
  assert.equal(without.oxfordCommaRate, 0)
  const neither = englishMetrics({ strings: ['Just one thing.'] })
  assert.equal(neither.oxfordCommaRate, null)
})

test('computeFingerprint marks english metrics N/A for other locales', () => {
  const cs = computeFingerprint({ strings: ['Vase kampan je naplanovana.'], headings: [], locale: 'cs' })
  assert.equal(cs.english, null)
  assert.ok(cs.universal.wordCount > 0)
  assert.equal(cs.sample.strings, 1)

  const en = computeFingerprint({ strings: ['Your campaign is scheduled.'], headings: [], locale: 'en' })
  assert.ok(en.english !== null)
  assert.equal(en.locale, 'en')
})
